services:
  db:                                    # Database service
    image: postgres:17.6-alpine          # Postgres image
    container_name: postgres_db_camrelay # Container name
    restart: unless-stopped              # Restart unless manually stopped
    env_file:
      - .env.dev                         # Load env variables from .env.dev
    ports:
      - "5432:5432"                      # Map host port to container port
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data
    healthcheck:                         # Check database readiness
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] # Verify DB connection
      interval: 10s                      # Check every 10 seconds
      timeout: 5s                        # Timeout after 5 seconds
      retries: 5                         # Retry 5 times
      start_period: 10s                  # Wait 10s before checks
    deploy:
      resources:                         # Limit container resources
        limits:
          cpus: "0.50"                   # Max 50% CPU
          memory: 1024M                  # Max 1GB RAM
        reservations:
          cpus: "0.25"                   # Reserve 25% CPU
          memory: 256M                   # Reserve 256MB RAM
    networks:
      - app-network                     # Use custom network
networks:
  app-network:                         # Custom network for services
    driver: bridge                     # Bridge network driver

volumes:
  db_data:                             # Named volume for database data